Added interlock summary and limits for RIKENFE
ISISComputingGroup/EPICS-transtechnik pull request #3
Opened 2022-11-30 12:51 UTC by LowriJenkins

Added interlock summary, limits, and tests for both for use with the RIKENFE OPI

2022-12-09 15:03 UTC, Tom-Willemsen requested changes

2022-12-09 15:03 UTC, Tom-Willemsen commented on transtechnikSup/transtechnik.db
> +    field(DESC, "Current Within Limit")
Isn't this current *outside* limits rather than within limits?

2022-12-09 15:03 UTC, Tom-Willemsen commented on transtechnikSup/transtechnik.db
> +    field(CALC, "(C<A)||(B<C)")
As above

2022-12-09 15:03 UTC, Tom-Willemsen commented on transtechnikSup/transtechnik.db
> +}
nit: newline
```suggestion
}

```

2022-12-09 15:03 UTC, Tom-Willemsen commented on transtechnikSup/transtechnik.db
> +record(calc, "$(P)ILK") {
Feels like this might be interesting `info(interest, ...)`?

Do we want to archive it too?

2022-12-09 15:03 UTC, Tom-Willemsen commented on transtechnikSup/transtechnik.db
> +    field(INP, "$(P)LIMIT CP")
```suggestion
    field(INP, "$(P)LIMIT CP MSI")
```

Maybe write/add to a test to prove that a disconnected emulator's `INVALID` alarm propagates up to this level correctly.

2022-12-12 08:35 UTC, LowriJenkins commented on transtechnikSup/transtechnik.db
> +record(calc, "$(P)ILK") {
I wasn't sure if it should be considered of interest when it was something specifcally used for one OPI thats just a summary of fields that are of interest, but if you think it is I can make it interest?

2022-12-15 14:49 UTC, Tom-Willemsen approved these changes

2022-12-15 14:49 UTC, merged